#!/bin/bash
rm -rf ./tmp

set -e

mkdir tmp
mkdir tmp/public tmp/src tmp/views
cp -rf ../../app/src/public/* ./tmp/public/
cp -rf ../../app/src/src/* ./tmp/src/
cp -rf ../../app/src/views/* ./tmp/views/
cp -rf ../../app/src/resources ./tmp/resources
cp -rf ../../app/src/.env_prod ./tmp/.env
COMMIT_HASH=`git rev-parse HEAD`
echo "{\"value\":\"${COMMIT_HASH}\"}" > ./tmp/src/revision.json
cp ../../app/src/package.json ./tmp/package.json
cp ../../app/src/.babelrc ./tmp/.babelrc
cp ../../app/docker/Dockerfile ./tmp/Dockerfile

pushd tmp

export AWS_ACCESS_KEY_ID=AKIAIPKZH7X4NJKN3DVQ
export AWS_SECRET_ACCESS_KEY=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
export AWS_DEFAULT_REGION=us-east-1

echo Get Docker Login commang from AWS
DOCKER_LOGIN=`aws ecr get-login`
echo Performing Docker Login to AWS
eval $DOCKER_LOGIN

docker rmi app-mdocs-co:latest || true
docker build -t app-mdocs-co .
docker tag -f app-mdocs-co:latest 067216503767.dkr.ecr.us-east-1.amazonaws.com/app-mdocs-co:latest
docker push 067216503767.dkr.ecr.us-east-1.amazonaws.com/app-mdocs-co:latest

popd

rm -rf ./tmp

# TASK_ARN=`aws ecs list-tasks --cluster app-mdocs-co --family app-mdocs-co-www | jq -r '.taskArns[0]'`
# aws ecs stop-task --cluster app-mdocs-co --task ${TASK_ARN}

# Update to latest
docker pull silintl/ecs-deploy
# Force AWS EC2 do Blue-Green deployment
docker run --rm \
-e "AWS_ACCESS_KEY_ID=AKIAIPKZH7X4NJKN3DVQ" \
-e "AWS_SECRET_ACCESS_KEY=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" \
-e "AWS_DEFAULT_REGION=us-east-1" \
silintl/ecs-deploy:latest -c app-mdocs-co -n www -i 067216503767.dkr.ecr.us-east-1.amazonaws.com/app-mdocs-co:latest

