#!/usr/bin/env bash

exec docker run --rm -it \
  --name mdocs-apps-nginx \
  -v "$(pwd)/nginx/conf":/opt/openresty/nginx/conf \
  -v "$(pwd)/nginx/html":/opt/openresty/nginx/html \
  -v "$(pwd)/nginx/lualib":/opt/openresty/nginx/lualib \
  -p 8080:8080 \
  067216503767.dkr.ecr.us-east-1.amazonaws.com/openresty-alpine:latest "$@"
